Proceso MEDIA_EDADES
	Definir EDAD,ACUMULADOR,NUM_PERSONAS Como Entero;
	DEFINIR MEDIA Como Real;
	ACUMULADOR<-0;
	NUM_PERSONAS<-0;
	Repetir
		Escribir "INGRESA TU EDAD";
		Leer EDAD;
		Si (EDAD > 0) Entonces
			ACUMULADOR<-ACUMULADOR+EDAD;
			NUM_PERSONAS<-NUM_PERSONAS+1;
		FINSI
	Hasta Que (EDAD<0)
	MEDIA<-ACUMULADOR/NUM_PERSONAS;
	Escribir "ESTA ES LA MEDIA DE EDAD. ",MEDIA;
FinProceso
