Proceso CALCULAR_RAIZ
	DEFINIR RAIZ_CUADRADA,RAIZ_CUBICA,NUM Como Real;
	Escribir "INGRESA UN NUMERO";
	Leer NUM;
	RAIZ_CUADRADA<- RAIZ(NUM);
	RAIZ_CUBICA<- NUM^(1/3);
	Escribir "ESTA ES LA RAIZ_CUADRADA: ",RAIZ_CUADRADA;
	Escribir "ESTA ES LA RAIZ_CUBICA: ",RAIZ_CUBICA;
FinProceso
