Proceso CELSIUS
	DEFINIR FARANHEI, CELSIUSS Como Real;
	Escribir "ESCRIBE CUANTOS FARANHEI TIENES";
	Leer FARANHEI;
	CELSIUSS<- (FARANHEI-32)*5/9;
	Escribir "ESTA ES TU CONVERSION: ", CELSIUSS,"C";
FinProceso
