Proceso EDESCUENTO
	Definir PRECIO, DESCUENTO Como Real;
	Escribir "INGRESA EL PRECIO";
	Leer PRECIO;
	DESCUENTO<- PRECIO * 0.15;
	Escribir "ESTE ES EL PRECIO ", PRECIO - DESCUENTO;
	Escribir "ESTE ES EL DESCUENTO ", DESCUENTO;
FinProceso
