Proceso DISTANCIA_PUNTOS
	DEFINIR X1,Y1,X2,Y2,DISTANCIA Como Real;
	Escribir "INGRESA LAS COORDENADAS DEL PUNTO 1";
	Leer X1,Y1;
	Escribir "INGRESA LAS COORDENADAS DEL PUNTO 2";
	Leer X2,Y2;
	DISTANCIA<-raiz((X1 - Y1)^2+(X2 - Y2)^2);
	Escribir "ESTA ES LA DISTANCIA: ",DISTANCIA;
FinProceso
