Proceso DISTANCIA_NUMERO
	DEFINIR NUM1, NUM2, DISTANCIA Como Entero;
	Escribir "INGRESA DOS NUMEROS Y TE MOSTRARE LA DISTANCIA QUE HAY ENTRE ELLOS";
	Leer NUM1,NUM2;
	DISTANCIA<-abs(NUM1 - NUM2);
	Escribir "ESTA ES LA DISTANCIA: ",DISTANCIA;
FinProceso
