Proceso METROS_KILOMETROS
	DEFINIR VELOCIDAD_MS, VELOCIDAD_KMH Como Real;
	Escribir "INGRESA LA VELOCIDASD DE METROS SPBRE SEGUNDSO(M/S)";
	Leer VELOCIDAD_MS;
	VELOCIDAD_KMH<- VELOCIDAD_MS*3.6;
	Escribir "ESTA ES TU VELOCIDAD EN KM/H: ",VELOCIDAD_KMH,"KM/H";
	
FinProceso
