Proceso PORCENTAJE_ASITENCIA
	DEFINIR HOM,MUJ, TOTAL Como Entero;
	DEFINIR PORCENTAJE_HOM, PORCENTAJE_MUJ Como Real;
	Escribir "EL NUMERO DE HOMBRES";
	Leer HOM;
	Escribir "NUMERO DE MUJERES";
	Leer MUJ;
	TOTAL<-HOM+MUJ;
	PORCENTAJE_HOM<- (HOM*100)/TOTAL;
	PORCENTAJE_MUJ<- (MUJ*100)/TOTAL;
	Escribir "ESTE ES EL PORCENTAJE DE HOMBRES: ", PORCENTAJE_HOM,"%";
	Escribir "ESTE ES EL PORCENTAJE DE MUJERES: ", PORCENTAJE_MUJ,"%";
FinProceso
