Proceso ULTUMA_CIFRA
	Definir NUM, ULTIMA Como Entero;
	Escribir "INGRESA UN NUMERO ENTERO DE VARIAS CIFRAS";
	Leer NUM;
	ULTIMA<- NUM MOD 10;
	Escribir "ESTA ES LA ULTIMA CIFRA DE TU NUMERO: ",ULTIMA;
	
FinProceso
